services:
  bot:
    container_name: tg-contacts-search-bot
    build:
      context: .
      target: final
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - APP_HASH=${APP_HASH}
      - APP_ID=${APP_ID}
      - PHONE=${PHONE}
      - PASSWORD=${PASSWORD}
      - SESSION_FOLDER=/app/sessions
    restart: unless-stopped
    volumes:
      - ./sessions:/app/sessions
